name: '.NET Deploy Web'
description: 'Builds and tests .NET projects'

inputs:
  artifact-name:
    description: 'Name of the published artifacts'
    required: false
    default: 'dotNetApp'
  target-directory:
    description: 'Path to the target directory of the application'
    required: true
  ssh-host:
    description: 'Ssh host'
    required: true
  ssh-username:
    description: 'Ssh username'
    required: true
  ssh-key:
    description: 'Ssh key'
    required: true
  kestrel-service:
    description: 'Name of the kestrel service'
    required: true

runs:
  using: composite
  steps:
  - name: Download artifact
    uses: actions/download-artifact@v4
    with:
      name: ${{ inputs.artifact-name }}
      path: ./

#  - name: show content
#    shell: bash
#    run: find . -ls

  - name: Upload artifacts to temporary folder
    uses: appleboy/scp-action@v1
    with:
        host: ${{ inputs.ssh-host }}
        username: ${{ inputs.ssh-username }}
        key: ${{ inputs.ssh-key }}
        source: "*"
        target: "${{ inputs.target-directory }}/next"
        rm: true

  - name: Upload artifacts to temporary folder
    uses: appleboy/ssh-action@v1
    with:
        host: ${{ inputs.ssh-host }}
        username: ${{ inputs.ssh-username }}
        key: ${{ inputs.ssh-key }}
        script: |
            # exit on any error
            set -e

            echo "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
            echo "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
            whoami
            echo "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
            echo "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
            groups
            echo "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
            echo "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
            ll ${{ inputs.target-directory }}
            echo "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
            echo "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
            ll ${{ inputs.target-directory }}/old
            echo "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
            echo "xxxxxxxxxxxxxxxxxxxxxxxxxxx"

            echo "Removing old versions"
            rm -rf ${{ inputs.target-directory }}/old

            echo "Switching current -> old"
            mv ${{ inputs.target-directory }}/current ${{ inputs.target-directory }}/old

            echo "Switching next -> current"
            mv ${{ inputs.target-directory }}/next ${{ inputs.target-directory }}/current

            echo "correcting permissions"
            chown -R $(stat -c "%U:%G" ${{ inputs.target-directory }}) ${{ inputs.target-directory }}

            echo "Restarting kestrel service"
            sudo systemctl restart ${{ inputs.kestrel-service }}
