name: '.NET Deploy Web'
description: 'Builds and tests .NET projects'

inputs:
  artifact-name:
    description: 'Name of the published artifacts'
    required: false
    default: 'dotNetApp'
  target-directory:
    description: 'Path to the target directory of the application'
    required: true
  ssh-host:
    description: 'Ssh host'
    required: true
  ssh-username:
    description: 'Ssh username'
    required: true
  ssh-key:
    description: 'Ssh key'
    required: true

runs:
  using: composite
  steps:
  - name: Download artifact
    uses: actions/download-artifact@v4
    with:
      name: ${{ inputs.artifact-name }}
      path: ./${{ inputs.artifact-name }}/

#  - name: show content
#    shell: bash
#    run: find . -ls

  - name: Upload artifacts to temporary folder
    uses: appleboy/scp-action@v1
    with:
        host: ${{ inputs.ssh-host }}
        username: ${{ inputs.ssh-username }}
        key: ${{ inputs.ssh-key }}
        source: "${{ inputs.artifact-name }}/*"
        target: "${{ inputs.target-directory }}/next"
        rm: true
