name: '.NET Deploy Web'
description: 'Deploys .NET projects'

inputs:
  artifact-name:
    description: 'Name of the published artifacts'
    required: false
    default: 'dotNetApp'
  target-directory:
    description: 'Path to the target directory of the application'
    required: true
  ssh-host:
    description: 'Ssh host'
    required: true
  ssh-username:
    description: 'Ssh username'
    required: true
  ssh-key:
    description: 'Ssh key'
    required: true
  kestrel-service:
    description: 'Name of the kestrel service'
    required: true
  internal-health-endpoint:
    description: 'Internal endpoint for health checks. Leave empty to skip checks'
    required: false
    default: ''
  health-check-retry-delay:
    description: 'Delay in seconds between retries of health checks (default: 10)'
    required: false
    default: '10'
  health-check-retry-amount:
    description: 'Amount of retries for health checks (default: 6)'
    required: false
    default: '6'

runs:
  using: composite
  steps:
  - name: Download artifact
    uses: actions/download-artifact@v4
    with:
      name: ${{ inputs.artifact-name }}
      path: ./

  - name: Upload artifacts to temporary folder
    uses: appleboy/scp-action@v1
    with:
        host: ${{ inputs.ssh-host }}
        username: ${{ inputs.ssh-username }}
        key: ${{ inputs.ssh-key }}
        source: "*"
        target: "${{ inputs.target-directory }}/next/web"
        rm: true

  - name: Upload artifacts to temporary folder
    uses: appleboy/ssh-action@v1
    with:
        host: ${{ inputs.ssh-host }}
        username: ${{ inputs.ssh-username }}
        key: ${{ inputs.ssh-key }}
        script: |
            # exit on any error
            set -e

            echo "removing old versions"
            rm -rf ${{ inputs.target-directory }}/old

            if [ -d "${{ inputs.target-directory }}/current/data" ]; then
              echo "found a data directory"
              echo "copy current data to upcoming version"
              cp -r ${{ inputs.target-directory }}/current/data ${{ inputs.target-directory }}/next
            fi

            echo "switching current -> old"
            mv ${{ inputs.target-directory }}/current ${{ inputs.target-directory }}/old

            echo "switching next -> current"
            mv ${{ inputs.target-directory }}/next ${{ inputs.target-directory }}/current

            echo "correcting permissions"
            sudo chmod 770 -R ${{ inputs.target-directory }}

            echo "correcting ownership"
            sudo chown -R $(stat -c "%U:%G" ${{ inputs.target-directory }}) ${{ inputs.target-directory }}

            echo "restarting kestrel service"
            sudo systemctl restart ${{ inputs.kestrel-service }}

            if [ -z "${{ inputs.internal-health-endpoint }}" ]; then
              echo "Skipping health check ('internal-health-endpoint' wasn't supplied)"              
            else
              MAX_RETRIES=${{ inputs.health-check-retry-amount }}
              RETRY_DELAY=${{ inputs.health-check-retry-delay }}
              
              for i in $(seq 1 $MAX_RETRIES); do
                if curl -f ${{ inputs.internal-health-endpoint }} > /dev/null 2>&1; then
                  echo "Health check passed! New version is running correctly."
                  break
                else
                  echo "Health check failed (attempt $i / $MAX_RETRIES)"
                  if [ $i -eq $MAX_RETRIES ]; then
                    echo "All health checks failed! Initiating automatic rollback..."
              
                    echo " - removing failed version"
                    rm -rf ${{ inputs.target-directory }}/current

                    echo " - enabling old version"
                    mv ${{ inputs.target-directory }}/old ${{ inputs.target-directory }}/current
                    
                    echo " - correcting permissions"
                    sudo chmod 770 -R ${{ inputs.target-directory }}
                    
                    echo " - correcting ownership"
                    sudo chown -R $(stat -c "%U:%G" ${{ inputs.target-directory }}) ${{ inputs.target-directory }}
                    
                    echo " - restarting kestrel service"
                    sudo systemctl restart ${{ inputs.kestrel-service }}
              
                    echo "Rollback completed. Service restored to previous version."
                    exit 1
                  else
                    echo "Waiting $RETRY_DELAY seconds before retry"
                    sleep $RETRY_DELAY
                  fi
                fi
              done
            fi
