name: '.NET Deploy Web'
description: 'Builds and tests .NET projects'

inputs:
  artifact-name:
    description: 'Name of the published artifacts'
    required: false
    default: 'dotNetApp'

runs:
  using: composite
  steps:
  - name: Download artifact
    uses: actions/download-artifact@v4
    with:
      name: ${{ inputs.artifact-name }}
      path: ./${{ inputs.artifact-name }}/

      
  - name: Upload artifacts to temporary folder
    uses: appleboy/scp-action@v1
    with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "./${{ inputs.artifact-name }}/*"
        target: "/{{ inputs.target_dir }}/next"
