name: '.NET Build'
description: 'Builds and tests .NET projects'

inputs:
  dotnet-version:
    description: '.NET version'
    required: false
    default: '9.0.x'
  build-configuration:
    description: 'Build configuration (e.g. Debug, Release)'
    required: false
    default: 'Release'
  build-filter:
    description: 'Build artifact (e.g. path to project / solution or filter (**/*.csproj)'
    required: false
    default: '**/*.csproj'
  enable-tests:
    description: 'Enable test execution'
    required: false
    default: 'true'
  test-filter:
    description: 'Build artifact (e.g. path to project / solution or filter (**/*.csproj)'
    required: false
    default: '**/*[Tt]ests/*.csproj'
  publish-filter:
    description: 'Artifact to be published'
    required: false
    default: '**/*.csproj'
  enable-publish:
    description: 'Enable publishing the created artifacts'
    required: false
    default: 'false'
  artifact-name:
    description: 'Name of the published artifacts'
    required: false
    default: 'dotNetApp'

runs:
  using: composite
  steps:
  - name: Setup .NET
    uses: actions/setup-dotnet@v5
    with:
      dotnet-version: ${{ inputs.dotnet-version }}

  - name: Restore dependencies
    shell: bash
    run: dotnet restore ${{ inputs.build-filter }}

  - name: Build
    shell: bash
    run: dotnet build ${{ inputs.build-filter }} --configuration ${{ inputs.build-configuration }} --no-restore

  - name: Test
    shell: bash
    if: ${{ inputs.enable-tests == 'true' }}
    run: |
      find . -type f -path '**/*[Tt]ests/*.csproj' -printf '%P\n' | while ifs= read -r project; do
        echo "Testing project: $project"
        dotnet test '$project' --configuration ${{ inputs.build-configuration }} --no-build --verbosity normal
      done

  - name: Publish
    shell: bash
    if: ${{ inputs.enable-publish == 'true'}}
    run: dotnet publish ${{ inputs.publish-filter }} --configuration ${{ inputs.build-configuration }} --output ./publish --no-build

  - name: Upload artifact
    if: ${{ inputs.enable-publish == 'true'}}
    uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.artifact-name }}
      path: ./publish/
      retention-days: 7
